# -*- coding: utf-8 -*-
"""Assignment_2_Dolly_Jha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4g76LNSgZsiXyJ9ETLg8fW3obTqWI72

##ASSIGNMENT 2:
Module 3: Control Structures in Python

Task 1: Check if a Number is Even or Odd
Problem Statement:  Write a Python program that:
1. 	Takes an integer input from the user.
2. 	Checks whether the number is even or odd using an if-else statement.
3. 	Displays the result accordingly.
"""

try:
  num = int(input("Enter a number: "))
  if num%2==0:
    print(f"Given Number is even {num}")
  else:
    print(f"Given Number is odd {num}")
except ValueError:
    print("Invalid input! Please enter numeric values only.")

"""#Task 2: Sum of Integers from 1 to 50 Using a Loop

Problem Statement: Write a Python program that:
1.   Uses a for loop to iterate over numbers from 1 to 50.
2.   Calculates the sum of all integers in this range.
3.   Displays the final sum.

"""

su = 0
for i in range(51):
  su = su +i
print(f"Sum of first 50 integers: {su}")